### PR TITLE
add a new branch for openwrt 19

### PR DESCRIPTION
**Pull request by rufengsuixing**

### CODE REVIEW

**Comment by chron0** [comment]
<3 - give me a ping when you think it's ready to be merged. Thx for sharing.

**Comment by rufengsuixing** [comment]
i don't so much familiar with css，it is a hard work for me,here is the difference between  version
Screenshot_2020-01-06-09-14-40-223_org mozilla firefox
Screenshot_2020-01-06-09-14-47-867_org mozilla firefox

**Comment by rufengsuixing** [comment]
i finish it,but there is still a lot of unused css selector , i have no idea about how to find and delete them

**Comment by rufengsuixing** [comment]
图片

图片

**Comment by chron0** [comment]
nice, ye, i know, openwrt theming is kinda masochistic in nature since they made a good job of making it absolutely cramped and difficult to do. Can I merge it?

**Comment by rufengsuixing** [comment]
create a new branch and merge it .Due to the modify in luci ,new theme can not support old version of luci

**Comment by chron0** [comment]
created openwrt-19 branch and merged your PR into it - this one was going against master.

**Pull request closed without merging**
